services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5500:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  node_app:
    container_name: postgres
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: